language: r
warnings_are_errors: true
sudo: required
r_packages:
  - devtools
bioc_packages:
  - BiocStyle

env:
  global:
    - CRAN=http://cran.rstudio.com
    - NOT_CRAN=true
    - _R_CHECK_CRAN_INCOMING_=false
    - _R_CHECK_FORCE_SUGGESTS_=false
